### PR TITLE
Bug 135

### PR DESCRIPTION
**Pull request by emymaria**
Autosuggestion seems to be happening as we type in when I tested. However when we erase everything the whole list was suggested, I removed this.

### CODE REVIEW

**Review by salmma — CHANGES_REQUESTED** [review]
when start typing in an already existing compute resource property type at **type name** field a suggestion of matching existing property types should be made - currently no suggestion is presented.

**Review by salmma — CHANGES_REQUESTED** [review]
the suggestion in the dialog is missing as soon as a compute resource property type does not have a description - it seems that the suggestion function cannot handle empty descriptions when searching through
Bildschirmfoto 2021-07-28 um 15 30 59

**Comment by emymaria** [comment]
I got suggestions for compute resource property without description also

**Comment by salmma** [comment]
Here is a demonstration. Maybe you can reproduce it.
https://user-images.githubusercontent.com/23473511/127989017-40fbe5f9-3e67-42bd-90bf-678dc2ee3338.mov

**Comment by emymaria** [comment]
Thank you. I finally managed to reproduce the bug. I have solved it.

**Pull request merged**
